# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Shooting' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shooting

  target 'ShootingTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'ShootingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Shooting-UAT' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shooting-UAT

end
